name: dotnet format check

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  dotnet-format:
    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Format
      run: dotnet format --verify-no-changes --verbosity diagnostic